name: Ping sitemap

on:
  push:
    branches: [ main ]

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Google with sitemap
        run: |
          if [ -z "${{ secrets.SITE_URL }}" ]; then
            echo "SITE_URL secret not set, skipping ping";
            exit 0;
          fi
          SITEMAP_URL="${{ secrets.SITE_URL }}/sitemap.xml"
          echo "Pinging Google: ${SITEMAP_URL}"
          curl -s "https://www.google.com/ping?sitemap=${SITEMAP_URL}" || true
